version: "3.8"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile_prod
    command: gunicorn hellodjango.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - logs_volume:/home/app/web/logs
    expose:
      - 8000
    env_file:
      - ./app/.env.prod
    depends_on:
      - db
      - redis
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/.env.prod.db
  
  ngnix:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - "1337:80"
    depends_on:
      - web
  
  celery:
    build:
      context: ./app
      dockerfile: Dockerfile_prod
    command: celery --app=hellodjango worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - logs_volume:/home/app/web/logs
    env_file:
      - ./app/.env.prod
    depends_on:
      - web
      - redis
  
  flower_dashboard:
    build:
      context: ./app
      dockerfile: Dockerfile_prod
    command: celery flower -A hellodjango --port=5555 --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    env_file:
      - ./app/.env.prod
    depends_on:
      - web
      - redis
      - celery
  
  redis:
    image: redis:7-alpine
      
#  memcached:
#    image: memcached:1.6.17-alpine3.16

volumes:
  postgres_data:
  static_volume:
  media_volume:
  logs_volume: